print("-----------Exercício 1----------")
print("Ciência da Computação - Unicsul")
print("--------------------------------")
print("-----------Exercício 2----------")
profissão = input("Digite sua profissão: ")
print("Sua profissão é", profissão)
print("--------------------------------")
print("-----------Exercício 3----------")
idade = input("Digite sua idade: ")
print("Sua idade é", idade)
print("--------------------------------")
print("-----------Exercício 4----------")
ultimoSobrenome = input("Digite seu último sobrenome: ")
print("Família", ultimoSobrenome)
print("--------------------------------")
print("-----------Exercício 5----------")
esporteFavorito = input("Digite seu esporte favorito: ")
print("Seu esporte favorito é", esporteFavorito)
print("--------------------------------")
